"""Which V_phi route supplies the dissolved-gas molar volume.

DEFAULT CHANGED 2026-07-25 (Mark's call): the delivered density now uses the
S&W modified-PR route with one dimensionless volume shift per gas, falling back
to the Plyasunov A12inf model where PR cannot be used. Plyasunov was the default
only because it was built first; where the two disagree, PR is the better of the
two against direct volumetric measurement.

WHY PR IS PREFERRED. Both routes were fitted, and PR wins on five of six gases
against direct densimetry (in-sample MAE: CH4 1.4 vs 1.5%, H2S 0.5 vs 1.4%,
N2 3.3 vs 4.9%, H2 5.1 vs 6.2%, C2H6 3.0 vs 3.4%; it loses CO2, 0.9 vs 0.7%).
It is also the only route that reproduces the H2S temperature trend: Murphy and
Gaines measured +0.69 cm3/mol between their cold and warm groups, PR gives +0.53
and Plyasunov is flat at +0.02. And it costs one number per gas against
Plyasunov's 35 at eight significant digits plus IAPWS-IF97.

NO TEMPERATURE HANDOVER (changed 2026-07-25, Mark's call). An earlier version
fell back to Plyasunov above 473 K, the top of the calibration data. It no longer
does: PR runs to the IAPWS-IF97 Region 1 ceiling of 623.15 K, which is what the
saturation-pressure guard needs and is near where a liquid water root ceases to
exist at all. A mid-range handover bought nothing and introduced a discontinuity
in the delivered default.

That is not an accuracy claim. Mark, 2026-07-25: "realistically I'm not vouching
for accuracy beyond 300-350 degF for any of this". 350 degF is 450 K, so the
practical envelope sits INSIDE the calibration data and the high-temperature
behaviour of either route is academic. Quote 450 K in a deliverable, not 623.
`pr_vphi_model.is_extrapolated()` reports where the shift is beyond its data.

WHERE PR STILL CANNOT BE USED, and what happens instead:
  * C3H8 and nC4H10 have no fitted volume shift - the calibration set has no
    direct volumetric data for them - so they always use Plyasunov.
  * Outside 273.15-623.15 K, above 100 MPa, or below the water saturation
    pressure, where V2inf is undefined because the solvent is vapour.

A CAVEAT THAT COMES WITH THE CHANGE. N2, H2 and C2H6 have volume shifts fitted
to a 298 K cluster only (`pr_vphi_model.UNCALIBRATED_IN_T`), so for those three
the temperature dependence of the DEFAULT route is now the EOS unaided rather
than calibrated. That was true of the optional route before and is unchanged in
substance; it matters more now that it is the default. Plyasunov remains
available for comparison and is one keyword away.
"""

# --- brine_props repository layout (inserted by build_public_repo.py) ---
import os as _os
import sys as _sys
_ROOT = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
_HERE = _os.path.dirname(_os.path.abspath(__file__))
# when run as a script, drop the script's own directory from sys.path so the
# subpackage name (e.g. `validation`) resolves to the package, not to a module
if _sys.path and _os.path.abspath(_sys.path[0]) == _HERE:
    _sys.path.pop(0)
if _ROOT not in _sys.path:
    _sys.path.insert(0, _ROOT)
_DATA = _os.path.join(_ROOT, 'data')
_RESULTS = _os.path.join(_ROOT, 'validation', 'results')
_FIGOUT = _os.path.join(_ROOT, 'figures', 'out')
_TABLES = _os.path.join(_ROOT, 'examples', 'tables')
for _d in (_RESULTS, _FIGOUT, _TABLES):
    _os.makedirs(_d, exist_ok=True)
# ------------------------------------------------------------------------

import brine_gas.plyasunov_model as _PLY
import brine_gas.pr_vphi_model as _PR

ROUTES = ('auto', 'pr', 'plyasunov')
DEFAULT_ROUTE = 'auto'


# ---------------------------------------------------------------- salt effect
# ADOPTED 2026-07-25 as an absolute additive term; FORM CHANGED to RELATIVE
# 2026-07-30 (Mark's call, after the collapse test showed the two frames
# statistically indistinguishable on the direct data once the KOH 5 M points
# are set aside - `salt_effect_collapse.py`, closed record section J).
#
# V_phi falls with salinity. The dimensionless fraction below is fixed
# ENTIRELY from direct measurement, with no parameter fitted to any
# brine-density data: the seven Tiepel & Gubbins (1972) KCl dilatometry
# points (Ar, CH4, C2H6 at 1-4 M), the same basis the earlier absolute law
# used. Generated by `relative_salt_shift.py` (fit RMS 0.55 pp):
#     V_eff = V_phi(T,P) * (1 + g(m)),  g(m) = -c*m/(1 + d*m)
# giving -1.52% at 1 molal and -5.27% at 5 molal (Tiepel's molar KCl
# concentrations converted to molality at 25 degC since 2026-09-05; the
# molar-as-molal fit gave -1.56% / -5.85%). For CO2 (V ~ 33-46
# cm3/mol) that is -0.5 to -2.7 cm3/mol, matching the superseded absolute
# law within the scatter of the direct evidence everywhere validated
# (Yan/Calabrese re-scores move < 0.3 pp; costing in relative_salt_shift.py).
# The relative form scales automatically with gas and state; the price is a
# larger untested correction for C3H8/nC4H10 (V ~ 73-77) and a T-dependence
# through V_phi(T,P) that no measurement tests either way (all direct data
# sit at 25-51.5 degC).
#
# The magnitude is known to about a factor of two: O'Sullivan's NaCl
# measurements sit shallower, Tiepel's KCl at this value, and the anchored
# Calabrese inversion between (-0.6 to -0.8 cm3/mol per molal; the steeper
# raw inversion slopes were shown 2026-07-30 to be per-fill baseline
# systematics - closed record section J).
#
# WHY NOT THE EOS's OWN SALINITY RESPONSE. The PR route accepts m_nacl through
# the S&W water alpha and kij, but that pathway yields only -0.03 to -0.07
# cm3/mol per molal, an order of magnitude too small, and it is linear where the
# measurements saturate. It is therefore left at zero and this term carries the
# whole effect, so there is no double counting.
SALT_C, SALT_D = 0.017061208, 0.12370899    # 8 sig digits, generated - do not retype


def salt_fraction(m_nacl):
    """Fractional change in V_phi from dissolved salt. Gas-generic, always <= 0."""
    m = max(float(m_nacl), 0.0)
    return -SALT_C * m / (1.0 + SALT_D * m)


def pr_applicable(gas, T, P):
    """True if the PR + VSHIFT route is calibrated for this gas and state."""
    try:
        _PR._check(gas, T, P)
        return True
    except (ValueError, KeyError):
        return False


def V_phi(gas, T, P, route=DEFAULT_ROUTE, m_nacl=0.0, salt_effect=True):
    """Dissolved-gas apparent molar volume at infinite dilution, cm3/mol.

    Args:
        gas: gas name string.
        T: K. P: MPa.
        route: 'auto' uses PR where it is calibrated and Plyasunov elsewhere;
            'pr' forces the PR route and raises outside its box; 'plyasunov'
            forces the A12inf model.
        m_nacl: NaCl molality. Applies the literature-anchored relative salt
            fraction (see `salt_fraction`); it is NOT passed to the EOS, whose
            own salinity response is an order of magnitude too small.
        salt_effect: set False to recover the freshwater V_phi.

    Returns:
        V_phi in cm3/mol.
    """
    if route not in ROUTES:
        raise ValueError(f'route must be one of {ROUTES}, got {route!r}')
    f = 1.0 + (salt_fraction(m_nacl) if salt_effect else 0.0)
    if route == 'plyasunov':
        return float(_PLY.V2_inf(gas, T, P)) * f
    if route == 'pr':
        return float(_PR.V2_inf(gas, T, P)) * f
    base = (float(_PR.V2_inf(gas, T, P)) if pr_applicable(gas, T, P)
            else float(_PLY.V2_inf(gas, T, P)))
    return base * f


def dV_phi_dp(gas, T, P, route=DEFAULT_ROUTE, m_nacl=0.0, salt_effect=True):
    """Pressure derivative of the delivered V_phi, cm3/mol/MPa, at fixed T,
    molality and infinite dilution: the closed-form PR derivative
    (`pr_vphi_model.dV2_inf_dp`) times the same salinity factor V_phi carries
    (the factor is pressure-independent). The PR route only: the Plyasunov
    fallback (C3H8, nC4H10) has no closed-form derivative here."""
    if route == 'plyasunov' or (route == 'auto' and not pr_applicable(gas, T, P)):
        raise ValueError(f'dV_phi_dp: no closed-form derivative on the Plyasunov route for {gas}')
    f = 1.0 + (salt_fraction(m_nacl) if salt_effect else 0.0)
    return float(_PR.dV2_inf_dp(gas, T, P)) * f


def route_used(gas, T, P, route=DEFAULT_ROUTE):
    """Which route `V_phi` would actually use - for reporting, never for logic."""
    if route == 'plyasunov':
        return 'plyasunov'
    if route == 'pr':
        return 'pr'
    return 'pr' if pr_applicable(gas, T, P) else 'plyasunov'


def boundary_step(gas, T, P, S=0.05, x2=0.01):
    """Density difference between the two routes, kg/m3 and %, at one state.

    Used by validation.py to pin the size of the step the 'auto' route takes at
    the edge of the PR calibration box.
    """
    from brine_gas.brine_properties import rho_brine
    from brine_gas.water_properties import MW_WATER
    from brine_gas.plyasunov_model import gas_mw

    rho1 = rho_brine(T, P, S) if S > 0 else None
    if rho1 is None:
        from brine_gas.water_properties import rho_w
        rho1 = rho_w(T, P)

    def _rho(v):
        W = (1.0 - x2) * MW_WATER / (1.0 - S)
        return (W + x2 * gas_mw(gas)) / (W / (rho1 / 1000.0) + x2 * v) * 1000.0

    a = _rho(V_phi(gas, T, P, 'plyasunov'))
    b = _rho(V_phi(gas, T, P, 'pr'))
    return b - a, 100.0 * (b / a - 1.0)
