"""Bignell (1987) H2 densities reduced to apparent molar volumes: a HELD-OUT check
of the H2 route (never fitted). Paper 61, Table I, 50 density differences of
H2-saturated water at 3.87-25.02 degC and atmospheric pressure, verified in
`bignell1987_density_data.json` (`ingest_bignell1987.py --check`).

Reduction (per temperature group, mean of the repeats): the dissolved amount at
0.101325 MPa total pressure comes from the Soreide-Whitson flash of the
companion refresh (framework='default', y_H2 = 1; the flash carries the water
vapour), and the exact inversion of the mass-volume balance gives

    V_phi = ((1 + m M)/(rho_w + drho) - 1/rho_w) / m       [m3/mol]

with m the H2 molality, M in kg/mol, rho_w from IAPWS-IF97 and drho Bignell's
density difference. The solubility is the weak link: +/-3% in x moves V_phi by
-/+0.6 cm3/mol, and Bignell's own literature Henry constant gives him 21.6 at
5 degC where the flash gives 23.0. The values are therefore held out, with the
solubility dependence stated, not fitted.

Result (2026-09-06): 21.3-23.0 cm3/mol, essentially flat (-0.07 cm3/mol/K),
where the route gives 24.1-25.0 rising; the route is +5% at 4 degC and +16% at
25 degC. At 25 degC Bignell's 21.6 sits below all three direct determinations
that set the shift (Zhou 23.1, Tiepel 25.2, Moore 26.7): the H2 inter-laboratory
spread at 298 K is 21.5-26.7 cm3/mol. A shift fitted to Bignell alone would be
-0.0150 (shipped -0.178503).

Run:  python3 bignell1987_h2_check.py          # recompute and compare
      python3 bignell1987_h2_check.py --check  # assert the pinned reduction
"""

# --- brine_props repository layout (inserted by build_public_repo.py) ---
import os as _os
import sys as _sys
_ROOT = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
_HERE = _os.path.dirname(_os.path.abspath(__file__))
# when run as a script, drop the script's own directory from sys.path so the
# subpackage name (e.g. `validation`) resolves to the package, not to a module
if _sys.path and _os.path.abspath(_sys.path[0]) == _HERE:
    _sys.path.pop(0)
if _ROOT not in _sys.path:
    _sys.path.insert(0, _ROOT)
_DATA = _os.path.join(_ROOT, 'data')
_RESULTS = _os.path.join(_ROOT, 'validation', 'results')
_FIGOUT = _os.path.join(_ROOT, 'figures', 'out')
_TABLES = _os.path.join(_ROOT, 'examples', 'tables')
for _d in (_RESULTS, _FIGOUT, _TABLES):
    _os.makedirs(_d, exist_ok=True)
# ------------------------------------------------------------------------

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))

P_ATM = 0.101325   # MPa; Table I gives no row pressures (ingestion note)

# Pinned reduction, (t_degC, n_repeats, V_phi cm3/mol), regenerated by main().
BIGNELL1987_H2 = [
    (3.87, 7, 22.99), (7.04, 3, 22.56), (9.00, 5, 22.35), (11.04, 4, 21.95),
    (12.96, 4, 22.16), (14.95, 3, 21.68), (16.93, 4, 21.49), (18.92, 4, 21.34),
    (20.98, 6, 21.69), (22.92, 3, 21.46), (22.93, 3, 21.45), (25.02, 4, 21.59),
]


def held_out_points():
    """(T_K, P_MPa, V_phi, source) tuples for fit_pr_vshift.HELD_OUT['H2']."""
    return [(round(t + 273.15, 2), P_ATM, V, 'Bignell 1987 (density, flash x)')
            for t, n, V in BIGNELL1987_H2]


def reduce():
    from pyrestoolbox import brine as rtb
    from brine_gas.water_properties import rho_w
    from brine_gas.plyasunov_model import gas_mw
    data = json.load(open(os.path.join(_DATA, 'bignell1987_density_data.json')))
    M = gas_mw('H2') / 1000.0
    groups = {}
    for r in data['table_I']['H2']:
        groups.setdefault(r['temperature_degC'], []).append(r['delta_rho_kg_m3'])
    out = []
    for t in sorted(groups):
        T = t + 273.15
        d = float(np.mean(groups[t]))
        x = float(rtb.SoreideWhitson(pres=P_ATM * 10, temp=t, ppm=0.0, metric=True,
                                     framework='default', y_H2=1.0).x['H2'])
        rw = rho_w(T, P_ATM)
        m = x / (1 - x) * 55.5084
        V = ((1 + m * M) / (rw + d) - 1 / rw) / m * 1e6
        Vlo = ((1 + 0.97 * m * M) / (rw + d) - 1 / rw) / (0.97 * m) * 1e6
        out.append((t, len(groups[t]), d, x, V, Vlo))
    return out


def main(check=False):
    from brine_gas.vphi_route import V_phi
    import brine_gas.pr_vphi_model as pr
    rows = reduce()
    print(f"{'t degC':>7} {'n':>2} {'drho kg/m3':>11} {'x_H2':>10} {'V_data':>7} {'V(x-3%)':>8} {'V_route':>8} {'route/data':>10}")
    devs, offs = [], []
    for t, n, d, x, V, Vlo in rows:
        T = t + 273.15
        vm = V_phi('H2', T, P_ATM)
        devs.append(100 * (vm / V - 1))
        offs.append(pr.V2_inf_raw('H2', T, P_ATM) - V)
        print(f'{t:7.2f} {n:2d} {d:11.5f} {x:10.3e} {V:7.2f} {Vlo:8.2f} {vm:8.2f} {devs[-1]:+9.1f}%')
    slope = np.polyfit([r[0] for r in rows], [r[4] for r in rows], 1)[0]
    s_alone = float(np.mean(offs) / pr.b_covolume('H2'))
    print(f'\nroute over data: mean {np.mean(devs):+.1f}%, range {min(devs):+.1f} to {max(devs):+.1f}%; '
          f'data slope {slope:+.3f} cm3/mol/K; shift fitted to this source alone {s_alone:+.6f} '
          f'(shipped {pr.VSHIFT["H2"]:+.6f})')
    ok = True
    for (t, n, d, x, V, Vlo), (tp, npin, Vpin) in zip(rows, BIGNELL1987_H2):
        if abs(t - tp) > 1e-9 or n != npin or abs(V - Vpin) > 0.006:
            ok = False
            print(f'  PIN MISMATCH at {t} degC: computed {V:.2f} (n={n}) vs pinned {Vpin} (n={npin})')
    print('pinned reduction', 'reproduces' if ok else 'DOES NOT reproduce')
    if check:
        assert ok and abs(np.mean(devs) - 12.4) < 0.15 and abs(s_alone + 0.0150) < 0.0005
        print('CHECK PASSED')
    return ok


if __name__ == '__main__':
    sys.exit(0 if main(check='--check' in sys.argv) else 1)
