"""Hebach, Oberhof & Dahmen (2004) CO2-saturated water densities reduced to
apparent molar volumes: a HELD-OUT check of the route (Paper 23, Table 1: 203
densities, 283-333 K, 1-31 MPa, u(rho) < 0.15%, 39 of them on the vapour-liquid
coexistence line). Table 1 was coordinate-parsed from the PDF text layer and
page-checked row by row against the rendered page on 2026-09-06 (all 203 rows
agree); the cached CSV is the checked copy.

The loading is NOT measured: x is the CO2 solubility in pure water from the
Soreide-Whitson flash (`framework='default'`) at each row's (T, p). By the
project's inclusion rule (direct volumetry and fresh-water inversions at MEASURED
loading are calibrated; solubility-derived volumes are held out) these rows
stay out of the fit.

Reduction per row, per kg water, IAPWS-IF97 water as the gas-free baseline:

    V_imp = ((1000 + m2 M)/rho - 1000/rho_w) / m2     [cm3/mol, rho in g/cm3]

The stated density uncertainty (0.15% of ~1000 kg/m3, so about 1.5 kg/m3)
enters the second term whole: at 284 K and x = 0.035 the CO2-induced density
change is about 13 kg/m3, so u(rho) alone is +/-2 to 3% on V_imp, and more
where x is smaller (the 323-333 K isotherms scatter by 2-2.5 cm3/mol). A 1%
error in the flash x moves V_imp by only about 0.2%.

Run:  python3 hebach2004_density_check.py          # recompute
      python3 hebach2004_density_check.py --check  # assert the pins
"""

# --- brine_props repository layout (inserted by build_public_repo.py) ---
import os as _os
import sys as _sys
_ROOT = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
_HERE = _os.path.dirname(_os.path.abspath(__file__))
# when run as a script, drop the script's own directory from sys.path so the
# subpackage name (e.g. `validation`) resolves to the package, not to a module
if _sys.path and _os.path.abspath(_sys.path[0]) == _HERE:
    _sys.path.pop(0)
if _ROOT not in _sys.path:
    _sys.path.insert(0, _ROOT)
_DATA = _os.path.join(_ROOT, 'data')
_RESULTS = _os.path.join(_ROOT, 'validation', 'results')
_FIGOUT = _os.path.join(_ROOT, 'figures', 'out')
_TABLES = _os.path.join(_ROOT, 'examples', 'tables')
for _d in (_RESULTS, _FIGOUT, _TABLES):
    _os.makedirs(_d, exist_ok=True)
# ------------------------------------------------------------------------

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))

# Pinned isotherm means (T_K rounded, mean p_MPa, V_imp mean, n), regenerated by
# main(); exported as held-out points at the isotherm's mean pressure.
ISOTHERMS = [
    (283, 4.4, 35.88, 4), (284, 13.2, 35.68, 23), (285, 9.0, 35.71, 22),
    (288, 9.6, 35.46, 19), (293, 13.3, 35.37, 37), (294, 15.4, 35.28, 16),
    (303, 12.3, 35.40, 23), (313, 14.4, 35.51, 15), (323, 14.4, 36.46, 15),
    (332, 14.4, 36.70, 15), (333, 13.4, 37.23, 14),
]
ROUTE_MEAN_DEV_ISO = -3.1     # % over the 164 isotherm rows (CO2 shift -0.070103)
ROUTE_MEAN_DEV_COEX = -4.8    # % over the 39 coexistence-line rows


def rows():
    csv = os.path.join(_DATA, 'hebach2004_table1_density.csv')
    return [tuple(map(float, l.split(','))) for l in open(csv).read().split('\n')[1:] if l]


def reduce():
    from brine_gas.water_properties import rho_w
    from brine_gas.plyasunov_model import gas_mw
    from brine_gas.vphi_route import V_phi
    from pyrestoolbox.brine import brine
    M = gas_mw('CO2')
    out = []
    for g, T, P, rho, coex in rows():
        sw = brine.SoreideWhitson(pres=P * 10, temp=T - 273.15, ppm=0, y_CO2=1.0,
                                  metric=True, framework='default')
        x = float(sw.x_total)
        rw = rho_w(T, P) / 1000.0
        m2 = x / (1 - x) * 55.5084
        V = ((1000 + m2 * M) / (rho / 1000.0) - 1000 / rw) / m2
        out.append((coex, T, P, rho, x, V, V_phi('CO2', T, P)))
    return np.array(out)


def held_out_points():
    return [(float(T), P, V, 'Hebach 2004 (density, x from flash)') for T, P, V, n in ISOTHERMS]


def main(check=False):
    a = reduce()
    dev = 100 * (a[:, 6] / a[:, 5] - 1)
    print(f"{'T K':>5} {'n':>3} {'p':>5} {'x':>7} {'V_imp':>7} {'sd':>5} {'route':>7} {'dev %':>7}")
    iso = []
    for T in sorted(set(np.round(a[:, 1]))):
        sel = a[np.round(a[:, 1]) == T]
        iso.append((int(T), sel[:, 2].mean(), sel[:, 5].mean(), len(sel)))
        print(f"{T:5.0f} {len(sel):3d} {sel[:, 2].mean():5.1f} {sel[:, 4].mean():7.4f} {sel[:, 5].mean():7.2f} "
              f"{sel[:, 5].std():5.2f} {sel[:, 6].mean():7.2f} {100 * (sel[:, 6].mean() / sel[:, 5].mean() - 1):+7.1f}")
    d_iso = dev[a[:, 0] == 0].mean()
    d_coex = dev[a[:, 0] == 1].mean()
    print(f'\nroute over implied: isotherm rows {d_iso:+.1f}% (n={int((a[:, 0] == 0).sum())}), '
          f'coexistence rows {d_coex:+.1f}% (n={int((a[:, 0] == 1).sum())}); '
          f'x range {a[:, 4].min():.4f}-{a[:, 4].max():.4f}')
    ok = all(abs(V - Vp) < 0.006 and n == npin and abs(P - Pp) < 0.06
             for (T, P, V, n), (Tp, Pp, Vp, npin) in zip(iso, ISOTHERMS))
    ok &= abs(d_iso - ROUTE_MEAN_DEV_ISO) < 0.06 and abs(d_coex - ROUTE_MEAN_DEV_COEX) < 0.06
    print('pins', 'reproduce' if ok else 'DO NOT reproduce')
    if check:
        assert ok
        print('CHECK PASSED')
    return ok


if __name__ == '__main__':
    sys.exit(0 if main(check='--check' in sys.argv) else 1)
