"""McBride-Wright, Maitland & Trusler (2015) CO2-water densities reduced to
apparent molar volumes, IN THE CO2 CALIBRATION since 2026-09-06 (Mark: adopt the
point-weighted refit); before that a held-out check of the route in FRESH water at
finite loading (Paper 21, Table 5: 98 densities at x = 0.0086/0.0168/0.0271,
274.7-449.2 K, 15-100 MPa, u(rho) = 0.4 kg/m3; the parent study of Calabrese).

Reduction per row, per kg water, with IAPWS-IF97 water as the gas-free baseline
(the authors' own choice: they augmented their fit with IAPWS-95 water):

    V_imp = ((1000 + m2 M)/rho - 1000/rho_w) / m2     [cm3/mol, rho in g/cm3]

Before the refit the route sat 1.6-4.1% BELOW the implied volumes on every
isotherm (mean -2.5%); with the 98 rows in the calibration the shift moved
-0.038965 -> -0.070103 and the mean deviation is -0.2%. at 274.7 K the three loadings
give 33.0-34.3 cm3/mol, so the cold-end CO2 volume is NOT uncertain by several
cm3/mol - Lauder's 28 and 44 are the outliers. The three loadings also give a
freshwater composition slope, dV_phi/dx = -28 to -61 per unit x on the
isotherms with all three (mean about -42), a third of Calabrese's -117 in
0.77 mol/kg brine. The x = 0.0086 rows carry +/-0.8 cm3/mol from the stated
density uncertainty alone.

Run:  python3 mcbridewright2015_density_check.py          # recompute
      python3 mcbridewright2015_density_check.py --check  # assert the pins
"""

# --- brine_props repository layout (inserted by build_public_repo.py) ---
import os as _os
import sys as _sys
_ROOT = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
_HERE = _os.path.dirname(_os.path.abspath(__file__))
# when run as a script, drop the script's own directory from sys.path so the
# subpackage name (e.g. `validation`) resolves to the package, not to a module
if _sys.path and _os.path.abspath(_sys.path[0]) == _HERE:
    _sys.path.pop(0)
if _ROOT not in _sys.path:
    _sys.path.insert(0, _ROOT)
_DATA = _os.path.join(_ROOT, 'data')
_RESULTS = _os.path.join(_ROOT, 'validation', 'results')
_FIGOUT = _os.path.join(_ROOT, 'figures', 'out')
_TABLES = _os.path.join(_ROOT, 'examples', 'tables')
for _d in (_RESULTS, _FIGOUT, _TABLES):
    _os.makedirs(_d, exist_ok=True)
# ------------------------------------------------------------------------

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))

# Pinned isotherm means (T_K rounded, mean p_MPa, V_imp mean over all loadings,
# n), regenerated by main(); exported as held-out points at the isotherm's mean
# pressure (the rows span 15-100 MPa).
ISOTHERMS = [
    (275, 56.1, 33.54, 14), (296, 56.1, 34.07, 14), (323, 58.7, 34.80, 12),
    (348, 62.7, 35.94, 11), (373, 62.7, 37.65, 11), (398, 74.0, 39.25, 3),
    (399, 57.6, 39.39, 9), (424, 61.7, 41.44, 12), (449, 61.7, 44.11, 12),
]
ROUTE_MEAN_DEV = -0.2      # % over all 98 rows, with the source IN the calibration (2026-09-06)
SLOPE_MEAN = -42.0         # cm3/mol per unit x, isotherms with three loadings


def rows():
    import validation.raw_viscosity_tables as R
    pdf = os.path.join(os.path.dirname(HERE), 'Papers',
                       '21_McBrideWright_2015_CO2_water_visc_dens_274-449K_100MPa.pdf')
    csv = os.path.join(_DATA, 'mcbridewright2015_table5_density.csv')
    if os.path.exists(csv):
        return [tuple(map(float, l.split(','))) for l in open(csv).read().split('\n')[1:] if l]
    out = R.parse_table((pdf, 5, 'Table 5.', (310.0, 1e4)))
    with open(csv, 'w') as f:
        f.write('x_CO2,T_K,p_MPa,rho_kg_m3\n')
        for x, T, P, rho in out:
            f.write(f'{x},{T},{P},{rho}\n')
    return out


def reduce():
    from brine_gas.water_properties import rho_w
    from brine_gas.plyasunov_model import gas_mw
    from brine_gas.vphi_route import V_phi
    M = gas_mw('CO2')
    out = []
    for x, T, P, rho in rows():
        Pm = min(P, 100.0)
        rw = rho_w(T, Pm) / 1000.0
        m2 = x / (1 - x) * 55.5084
        V = ((1000 + m2 * M) / (rho / 1000.0) - 1000 / rw) / m2
        out.append((x, T, P, rho, V, V_phi('CO2', T, Pm)))
    return np.array(out)


def held_out_points():
    return [(float(T), P, V, 'McBride-Wright 2015 (density, measured x)') for T, P, V, n in ISOTHERMS]


def main(check=False):
    a = reduce()
    dev = 100 * (a[:, 5] / a[:, 4] - 1)
    print(f"{'T K':>5} {'n':>3} {'V_imp':>7} {'route':>7} {'dev %':>7} {'dV/dx':>7}")
    iso = []
    for T in sorted(set(np.round(a[:, 1]))):
        sel = a[np.round(a[:, 1]) == T]
        xs = sel[:, 0]
        slope = np.polyfit(xs, sel[:, 4], 1)[0] if len(set(xs)) > 2 else float('nan')
        iso.append((int(T), sel[:, 4].mean(), len(sel), slope))
        print(f"{T:5.0f} {len(sel):3d} {sel[:, 4].mean():7.2f} {sel[:, 5].mean():7.2f} "
              f"{100 * (sel[:, 5].mean() / sel[:, 4].mean() - 1):+7.1f} {slope:+7.0f}")
    slopes = [s_ for *_, s_ in iso if not np.isnan(s_)]
    print(f'\nroute over implied: mean {dev.mean():+.1f}%, range {dev.min():+.1f} to {dev.max():+.1f}% (n={len(a)}); '
          f'freshwater slope mean {np.mean(slopes):+.0f} cm3/mol per unit x over {len(slopes)} isotherms')
    cold = a[np.round(a[:, 1]) == 275]
    print(f'274.7 K: implied {cold[:, 4].min():.1f}-{cold[:, 4].max():.1f} cm3/mol over three loadings')
    ok = all(abs(V - Vp) < 0.006 and n == npin for (T, V, n, _), (Tp, Pp, Vp, npin) in zip(iso, ISOTHERMS))
    ok &= abs(dev.mean() - ROUTE_MEAN_DEV) < 0.06 and abs(np.mean(slopes) - SLOPE_MEAN) < 1.0
    print('pins', 'reproduce' if ok else 'DO NOT reproduce')
    if check:
        assert ok
        print('CHECK PASSED')
    return ok


if __name__ == '__main__':
    sys.exit(0 if main(check='--check' in sys.argv) else 1)
